version: "3.8"

services:
  web:
    build:
      context: .
      args:
        DATABASE_URL: postgresql://vladsoruk:TbdEe4YdDUbEZCJrOrQiuBKGZE3JrbWp@dpg-d1r7fg8dl3ps73f5l6s0-a.frankfurt-postgres.render.com/school_61mx
    container_name: nextjs_app
    environment:
      - DATABASE_URL: postgresql://vladsoruk:TbdEe4YdDUbEZCJrOrQiuBKGZE3JrbWp@dpg-d1r7fg8dl3ps73f5l6s0-a.frankfurt-postgres.render.com/school_61mx
    ports:
      - "3000:3000"
